import type { FacilityDef } from '../types';

export const FACILITIES: Record<string, FacilityDef> = {
  coaster_basic: {
    id: 'coaster_basic',
    name: '基础过山车',
    category: 'thrill',
    sizeX: 6,
    sizeZ: 12,
    buildCost: 2500,
    monthlyUpkeep: 80,
    excitement: 8,
    nausea: 6,
    appeal: 90,
  },
  pirate_ship: {
    id: 'pirate_ship',
    name: '海盗船',
    category: 'thrill',
    sizeX: 4,
    sizeZ: 4,
    buildCost: 1200,
    monthlyUpkeep: 40,
    excitement: 6,
    nausea: 5,
    appeal: 70,
  },
  merry_go_round: {
    id: 'merry_go_round',
    name: '旋转木马',
    category: 'gentle',
    sizeX: 3,
    sizeZ: 3,
    buildCost: 600,
    monthlyUpkeep: 15,
    excitement: 2,
    nausea: 1,
    appeal: 45,
  },
  ferris_wheel: {
    id: 'ferris_wheel',
    name: '摩天轮',
    category: 'gentle',
    sizeX: 5,
    sizeZ: 5,
    buildCost: 1800,
    monthlyUpkeep: 50,
    excitement: 3,
    nausea: 2,
    appeal: 65,
  },
  burger_stall: {
    id: 'burger_stall',
    name: '薯条摊',
    category: 'shop',
    sizeX: 2,
    sizeZ: 2,
    buildCost: 300,
    monthlyUpkeep: 10,
    appeal: 30, // Passive appeal
  },
  restroom: {
    id: 'restroom',
    name: '洗手间',
    category: 'facility',
    sizeX: 2,
    sizeZ: 3,
    buildCost: 400,
    monthlyUpkeep: 20,
    appeal: 10,
  },
  bench: {
    id: 'bench',
    name: '长椅',
    category: 'facility',
    sizeX: 1,
    sizeZ: 1,
    buildCost: 50,
    monthlyUpkeep: 0,
    appeal: 5,
  },
};
